### ISSUE TITLE
Users managament

### ISSUE THREAD

**Issue by ariefdarmawan** [eaciit/mq#17]
Add command

```
addUser(username,password,isadmin) --> create new user (only admin)
removeUser(username1,username2,username3) --> delete user (only admin)
changePassword(password) --> change current user password
updateUser(username,password,isadmin) --> update existing user
```

Also pls create new screen on mqmonitor to manage user

**Comment by sugab** [comment]
updateUser(username,password,isadmin)
for update existing user it should be only admin right? Because it can update user role.

**Comment by ghost** [comment]
Yes

*\* sent from phone, apologize should there be typo **

Arief Darmawan
Co-Founder, Product Development
EACIIT - Enhancing Enterprise Value
http://www.eaciit.com
+628118097897
+6597789935

On 15 Jun 2015, at 09.42, Bagus Cahyono <notifications@github.com<mailto:notifications@github.com>> wrote:

updateUser(username,password,isadmin)
for update existing user it should be only admin right? Because it can update user role.

##
